# Data Type

# # Data Types esc + m used for heading

In [13]:
# use shift + tab for info
import numpy as np

a1 = np.array(
    [1,2,3]
)
a1

a2 = np.array([[1, 2.0, 3],
              [4, 5, 6.5]])
a2

import numpy as np

a3 = np.array([
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18],
                [7, 8, 9]]
             ])
#3 blocks 4 rows 3 columns
print(a3)
print("Shape:", a3.shape)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [ 7  8  9]]]
Shape: (3, 4, 3)


In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [17]:
a3.size

36

In [18]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
arr = np.random.rand(2,3)
print(arr)

[[0.91625514 0.96986846 0.70297857]
 [0.24539068 0.20945428 0.28195779]]


In [28]:
print(np.arange(1, 11, 2))

[1 3 5 7 9]


In [32]:
rng = np.random.default_rng(seed = 42)
rng.random((3,2))

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803],
       [0.09417735, 0.97562235]])

# Dot product vs Element wise multiplication

In [10]:
import numpy as np
np.random.seed(0)

mat1 = np.random.randint(10,size = (5,3))
mat2 = np.random.randint(10,size = (5,3))
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [9]:
mat1 * mat2 #elemental

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [13]:

np.dot(mat1,mat2.T) #dot product

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Broadcasting

In [16]:
#dimension should be equal, one of them is 1
# Broadcasting is a set of rules that allow operations on arrays of different shapes and sizes without explicitly copying data.
# It "stretches" the smaller array across the larger one so you can do element-wise operations seamlessly.


ex_arr1 = np.array([1,2,3])
ex_arr2 = np.array([[1],
                    [2],
                    [3]])
ex_arr1.shape,ex_arr2.shape

((3,), (3, 1))

In [17]:
ex_arr1 + ex_arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [18]:
ex_arr1 * ex_arr2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])